services:
  - type: web
    name: session-manager
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python session_manager.py
    envVars:
      - key: API_ID
        value: 23721778
      - key: API_HASH
        value: 7935a656311ab4e500294b22d6b6c7f6
      - key: PORT
        value: 5000
